### ISSUE TITLE
How to catch Validator error

### ISSUE THREAD

**Issue by kirill-ratkin** [lwinterface/panini#224]
In case of validation error a log message appears in console.
But example says no about how to catch the exception.
Could you add such logic to example or say couple words here how to do it?

I try to override method `validated_message` in my custom validator class inherited from `Validator.`
It doesn't work :(.

**Comment by kirill-ratkin** [comment]
I just did minimal changes in pull request - https://github.com/lwinterface/panini/pull/225 .
See it please, maybe it helps.

**Comment by artas728** [comment]
Hello @kirill-ratkin 
Indeed, catching a validator exception looks like a useful feature. 
I'll check your PR soon

**Comment by artas728** [comment]
@kirill-ratkin just checked PR #225 
The thing is such implementation breaks all listener functions that don’t have an argument `validation_report`. 
I would consider adding `validation_error_cb` as an argument for the listener decorator. For example:

```python
async def custom_validation_error_cb(msg):
    # custom staff
    return {"success": False, "error": ...}

@app.listen("some.subject", validator=SomeValidator, validation_error_cb=custom_validation_error_cb)
async def foo(msg):
    log.info(f"got message {msg.data}")
    await asyncio.sleep(1)
```

What do you think? Would it be convenient for your case?

**Comment by kirill-ratkin** [comment]
Hi.
Yes. Good idea to add decorator parameter. It's better than mine solution.
What do you think to do with wrapped function call in case of validation error happened?

For my perpective wrapped functoin should not be called in this case and custom_validation_error_cb should be responsible for error handling. In my case I'll inform sender in reply about validation error.

Good idea!

**Comment by artas728** [comment]
We will think about a wrapped function.

I can't guarantee but i think we will release the new version by the end of next week, the new version will include the validation error callback feature.

**Comment by artas728** [comment]
#227  Update in new panini release - v0.7.1
