### ISSUE TITLE
Exception DataTypeError happens but not catch

### ISSUE THREAD

**Issue by kirill-ratkin** [lwinterface/panini#230]
Hello.

I met case case where DataTypeError raises but there is not places where it's catched

Maybe function '_publish' is good place for it.
https://github.com/lwinterface/panini/blob/master/panini/managers/nats_client.py#L270

BR

**Comment by artas728** [comment]
Hi @kirill-ratkin 
Not sure if I understood your suggestion
Currently you can catch it by wrapping by try/except like:
 `
        try:
            await app.publish(subject="some.publish.subject", message=wrong_type_message))
        except DataTypeError:
            # something you want to do in this case
 `
 
 Could you provide any example how you want to catch it?

**Comment by kirill-ratkin** [comment]
Hmm... 

You are right but I met strange behaviour when every incomming message processed but raised this exception.
And I recreate virtualenv and can't reproduce this again.

Thank you for response and advise!
