### ISSUE TITLE
Custom Logger without files on a file system

### ISSUE THREAD

**Issue by kirill-ratkin** [lwinterface/panini#231]
Hi.

I'm trying to make custom logger config. I have constraint in my private cloud which doesn't allow me to write something inside docker container (filesystem is mounted in RO mode).

So I want to make custom logger configuration to output all logs to console (after that devops engineers transfer it to ELS).

Also I have to log additional fields to console.

So I create my custom formatter and add it to log_config.json

Here it is

```
{
  "version": 1,
  "disable_existing_loggers": true,
  "formatters": {
    "detailed": {
      "class": "pmp.fmt.PMOJsonFormatter",
      "format": "%(level)s %(timestamp)s %(service)s %(subsystem)s %(request_id)s %(session_id)s %(task_id)s %(method)s %(message)s %(detail) %(name)s %(filename)s %(lineno)s"
    },
    "simple": {
      "class": "logging.Formatter",
      "format": "%(asctime)s %(name)-15s %(levelname)-8s %(message)s"
    }
  },
  "handlers": {
    "console": {
      "class": "logging.StreamHandler",
      "level": "DEBUG",
      "formatter": "detailed",
      "stream": "ext://sys.stdout"
    }
  },
  "loggers": {
    "PMP": {
      "handlers": [
        "console"
      ]
    }
  },
  "root": {
    "level": "DEBUG",
    "handlers": [
	"console"
    ]
  }
}
```

(Here PMP is my application)

And everything work well but framework creates directory 'logs' with files 'panin.log' and 'inter_services_request.log'.
In parallel log strings appears on console as I expected.

I also tried to make log handlers with name 'panini' in log_config.json
```
    "panini": {
      "class": "logging.StreamHandler",
      "level": "DEBUG",
      "formatter": "detailed",
      "stream": "ext://sys.stdout"
    }
```
But in this case exception happened because 'panini' handler has to have field 'filename'.

So my question is ... how to configure custom logger without any files on disk?

**Comment by artas728** [comment]
Hello
Here is an example of how to create a custom logger from your config

```python

import logging
from typing import Dict

def make_logger(logger_config: Dict):
    logging.config.dictConfig(logger_config)
    logger = logging.getLogger(None)
    return logger

logger = make_logger(logger_config=your_logging_config)

app = panini_app.App(
    service_name="your_app",
    servers=["127.0.0.1:4222"],
    custom_logger=logger,
)

assert logger == app.logger
```

Let me know if something unclear

**Comment by kirill-ratkin** [comment]
Hi,
I change a bit your snippet and it works.

Thank you so much.
