### ISSUE TITLE
How to deliver build-in middlewares?

### ISSUE THREAD

**Issue by artas728** [lwinterface/panini#50]
- where to store
- how to initialize
- how to handle it if build-in middleware required periodic task

**Comment by danylott** [comment]
The first thing on the mind:
- where to store: 
middleware package in panini
- how to initialise: 
Add method at just the beginning of the app._start(), that adds default middlewares
- how to handle periodic tasks:
app object can be passed to the middleware class and from there create 1 more timer task using app object (if our interface allow it)

**Comment by artas728** [comment]
I think we are good here
