### ISSUE TITLE
Use labels in ListenPerformanceMonitoring middleware

### ISSUE THREAD

**Issue by artas728** [lwinterface/panini#81]
Use single name but different labels for metrics:
- app_name
- client_id
- subject
- metric_key_suffix(?)

**Comment by danylott** [comment]
How do you think, does this approach conflict with [not overuse labels](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels)?

**Comment by artas728** [comment]
we could remove metric_key_suffix

**Comment by artas728** [comment]
or even better, let the user decide which labels from our list he wants
