### ISSUE TITLE
RuntimeWarning in time sending panini_event.*.*.started with NATSTimeoutMiddleware

### ISSUE THREAD

**Issue by oleksii-v** [lwinterface/panini#98]
Try to add NATSTimeoutMiddleware and run the app

There is a warning:

panini/panini/app.py:215: RuntimeWarning: coroutine '_MiddlewareManager._wrap_function_by_middleware.<locals>.wrap_function_by_send_middleware.<locals>.aio_next_wrapper' was never awaited
  self.connector.publish_sync(f'panini_events.{self.service_name}.{self.client_id}.started', {})
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by danylott** [comment]
Fixed, by using low-level publish from nats aio
